export const ProductsData = [
  {
    id: 1,
    title: "BIND UP BACKPACK BLACK EDITION/ バックパック リュック",
    price: 25000,
    image: "./images/01.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "フロントにボードストラップを付けた上質感とストリートスタイルを融合させたバックパックフロントポケットはコの字にしており細かいモノの出し入れもしやすくしております。背面とストラップの裏側には、クッション性のあるメッシュ素材を使用。",
  },
  {
    id: 2,
    title: "DOUBLE BELT ZONE MIX DAYPACK BLACK EDITION/ デイパック/リュック",
    price: 18000,
    image: "./images/02.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "MAKAVELICの知名度をあげた立役者であるZONEMIXをオールブラックにして再登場。膨らみを持たせることで厚みのある物を入れても形が崩れ難くなったフラップ部分、入れた物が見えてさらに出し入れがしやすくなったサイドポケット。",
  },
  {
    id: 3,
    title: "DOUBLE LINE BACKPACK BLACK EDITION / バックパック/リュック",
    price: 22000,
    image: "./images/03.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "フロントの二本のレザーのラインが幅広いスタイルに馴染む大人バックパック。ロゴネームは、よりシックな印象を与えてくれる、ブラックロゴ仕様。24Lと容量も多くポケットが充実しているので、アイテム出し入れがスムーズに行えます。",
  },
  {
    id: 4,
    title: "【WEB限定】TIMÓN BACKPACK BLACK EDITION / バックパック/リュック",
    price: 27000,
    image: "./images/04.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "本体には高密度ナイロン生地 N/ROBIC を使用。一般のナイロンツイルと比べ経糸を細くし ている為、サテン織とは異なる落ち着いた光沢とドレープ感が出るようになっています。 また、ほつれ止めとしてソフトアクリルコーティングを施しています。",
  },
  {
    id: 5,
    title: "RECTANGLE DAYPACK / レクタングル デイパック/リュック",
    price: 18000,
    image: "./images/05.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "フロントにボードストラップを付けた上質感とストリートスタイルを融合させたバックパックフロントポケットはコの字にしており細かいモノの出し入れもしやすくしております。背面とストラップの裏側には、クッション性のあるメッシュ素材を使用。",
  },
  {
    id: 6,
    title: "【予約】DOUBLE BELT PMD MIX DAYPACK / デイパック/リュック",
    price: 16000,
    image: "./images/06.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "MAKAVELICの知名度をあげた立役者であるZONEMIXをオールブラックにして再登場。膨らみを持たせることで厚みのある物を入れても形が崩れ難くなったフラップ部分、入れた物が見えてさらに出し入れがしやすくなったサイドポケット。",
  },
  {
    id: 7,
    title: "【予約】DOUBLE BELT PMD MIX DAYPACK / デイパック/リュック",
    price: 19000,
    image: "./images/07.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "フロントの二本のレザーのラインが幅広いスタイルに馴染む大人バックパック。ロゴネームは、よりシックな印象を与えてくれる、ブラックロゴ仕様。24Lと容量も多くポケットが充実しているので、アイテム出し入れがスムーズに行えます。",
  },
  {
    id: 8,
    title: "SUPERIORITY BIND UP 2 BACKPACK / バックパック/リュック",
    price: 23000,
    image: "./images/08.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "本体には高密度ナイロン生地 N/ROBIC を使用。一般のナイロンツイルと比べ経糸を細くし ている為、サテン織とは異なる落ち着いた光沢とドレープ感が出るようになっています。 また、ほつれ止めとしてソフトアクリルコーティングを施しています。",
  },
  {
    id: 9,
    title: "TRUCKS GARAGE BODY BAG/ ボディバック",
    price: 11000,
    image: "./images/09.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "素材は摩擦引き裂けに強く、ペットボトルのリサイクル糸を使ったエコ素材を採用。軽量かつスポーティーなデザインでタウンユーズに最適です。",
  },
  {
    id: 10,
    title: "TRUCKS GARAGE DAYPACK/ デイパック/リュック",
    price: 16000,
    image: "./images/10.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "フロントのボードストラップとメッシュポケットがスポーティーな印象のデイパックです。",
  },
  {
    id: 11,
    title: "TRUCKS GARAGE MESSENGER BAG /メッセンジャーバック",
    price: 13000,
    image: "./images/11.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "二重に重なったフラップポケットが眼を惹くミニメッセンジャーバッグです。素材は摩擦引き裂けに強く、ペットボトルのリサイクル糸を使ったエコ素材を採用。",
  },
  {
    id: 12,
    title: "MAKAVELIC NECKSTRAP WALLET/ウォレット/財布",
    price: 9000,
    image: "./images/12.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "自転車やフェス等アクティブなシーンで活躍するネックストラップ付ウォレットです。本体は撥水加工がされており、素材は摩擦引き裂けに強く、ペットボトルのリサイクル糸を使ったエコ素材を採用。",
  },
  {
    id: 13,
    title: "FLIGHT SHOLDER BAG/ フライト ショルダーバック",
    price: 12000,
    image: "./images/13.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "リタリーテイストが人気のヘルメットバッグをミニショルダーにアレンジした限定モデルです。素材は落ち着いた光沢がある高密度ナイロンを仕様。弱撥水加工が施されており、アクティブなシーンでもお使い頂けます。",
  },
  {
    id: 14,
    title: "X-DESIGN SHOULDER BAG",
    price: 15000,
    image: "./images/14.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: " X-DESIGNから、機能性、耐久性の他にファッション性を更に追求した2021AW新作ショルダーバックが登場。高密度ナイロン生地N/ROBICを使用したショルダーバックはシンプルなデザインの中に、多くの機能性を兼ね備えました。",
  },
  {
    id: 15,
    title: "FLIGHT TOTE BAG/ フライトトートバック",
    price: 16000,
    image: "./images/15.jpeg",
    color1: "ブラック",
    color2: "ホワイト",
    color3: "グレー",
    message: "オンオフ問わず人気のヘルメットバッグをサイズダウンすることで、スタイリッシュで洗練された印象に。表面に大小4つのポケット、中はラップトップ収納もあり使い勝手も抜群です。素材は落ち着いた光沢がある高密度ナイロンを仕様。",
  },
];